export const cardStyle = {
  padding: "20px",
  margin: "10px",
  backgroundColor: "white",
  border: "2px solid black",
  borderRadius: "10px",
  width: "80px",
  height: "120px",
  display: "flex",
  flexDirection: "column",
  justifyContent: "space-between",
  alignItems: "center",
  fontSize: "24px",
  userSelect: "none",
  position: "relative",
} as const;
