import { Bera } from "./constants";

export enum BeraType {
  ADD_CHIPS = "ADD_CHIPS",
  ADD_MULT = "ADD_MULT",
  ADD_GOLD = "ADD_GOLD",
  MUL_MULT = "MUL_MULT",
  GEN_FLOWER = "GEN_FLOWER",
  GEN_MEME = "GEN_MEME",
  GEN_STICKER = "GEN_STICKER",
  GEN_CARD = "GEN_CARD",
  RETRIGGER = "RETRIGGER",
  INCREASE_CHIPS = "INCREASE_CHIPS",
  INCREASE_MULT = "INCREASE_MULT",
}

export enum BeraAction {
  INDEP = "INDEP",
  ON_HELD = "ON_HELD",
  ON_PLAYED = "ON_PLAYED",
  ON_DISCARD = "ON_DISCARD",
  ON_SCORED = "ON_SCORED",
  ON_REMOVED = "ON_REMOVED",
  ON_ADDED = "ON_ADDED",
  ON_ENDED = "ON_ENDED",
}

export enum BeraRarity {
  COMMON = "COMMON",
  UNCOMMON = "UNCOMMON",
  RARE = "RARE",
  EPIC = "EPIC",
  LEGENDARY = "LEGENDARY",
}

export const BERA_STATS = {
  [Bera.BABY]: {
    name: "Baby",
    description: "+4 Mult",
    cost: 2,
    rarity: BeraRarity.COMMON,
    values: [4, 8, 16],
    type: BeraType.ADD_MULT,
    action: BeraAction.INDEP,
  },
  [Bera.HEART]: {
    name: "Heart",
    description:
      "Played cards with Heart suit icon Heart suit give {{value}} Mult when scored",
    cost: 5,
    rarity: BeraRarity.COMMON,
    values: [3, 4, 5],
    type: BeraType.ADD_MULT,
    action: BeraAction.ON_SCORED,
  },
  [Bera.DIAMOND]: {
    name: "Diamond",
    description:
      "Played cards with Diamond suit icon give {{value}} Mult when scored",
    cost: 5,
    rarity: BeraRarity.COMMON,
    values: [3, 4, 5],
    type: BeraType.ADD_MULT,
    action: BeraAction.ON_SCORED,
  },
  [Bera.CLUB]: {
    name: "Club",
    description:
      "Played cards with Club suit icon give +{{value}} Mult when scored",
    cost: 5,
    rarity: BeraRarity.COMMON,
    values: [3, 4, 5],
    type: BeraType.ADD_MULT,
    action: BeraAction.ON_SCORED,
  },
  [Bera.SPADE]: {
    name: "Spade",
    description:
      "Played cards with Spade suit icon give +{{value}} Mult when scored",
    cost: 5,
    rarity: BeraRarity.COMMON,
    values: [3, 4, 5],
    type: BeraType.ADD_MULT,
    action: BeraAction.ON_SCORED,
  },
  [Bera.TWINS]: {
    name: "Twins",
    description: "+{{value}} Chips if played hand contains a Pair",
    cost: 3,
    rarity: BeraRarity.COMMON,
    values: [50, 75, 100],
    type: BeraType.ADD_CHIPS,
    action: BeraAction.INDEP,
  },
  [Bera.TRIPLETS]: {
    name: "Triplets",
    description: "+{{value}} Chips if played hand contains a Three of a Kind",
    cost: 4,
    rarity: BeraRarity.COMMON,
    values: [100, 150, 200],
    type: BeraType.ADD_CHIPS,
    action: BeraAction.INDEP,
  },
  [Bera.CLIMB]: {
    name: "Climb",
    description: "+{{value}} Chips if played hand contains a Straight",
    cost: 4,
    rarity: BeraRarity.COMMON,
    values: [100, 150, 200],
    type: BeraType.ADD_CHIPS,
    action: BeraAction.INDEP,
  },
  [Bera.UNIFORM]: {
    name: "Uniform",
    description: "+{{value}} Chips if played hand contains a Flush",
    cost: 4,
    rarity: BeraRarity.COMMON,
    values: [80, 120, 160],
    type: BeraType.ADD_CHIPS,
    action: BeraAction.INDEP,
  },
  [Bera.DOUBLES]: {
    name: "Doubles",
    description: "+{{value}} Mult if played hand contains a Pair",
    cost: 3,
    rarity: BeraRarity.COMMON,
    values: [8, 12, 16],
    type: BeraType.ADD_MULT,
    action: BeraAction.INDEP,
  },
  [Bera.FAMILY]: {
    name: "Family",
    description: "+{{value}} Mult if played hand contains a Three of a Kind",
    cost: 4,
    rarity: BeraRarity.COMMON,
    values: [12, 16, 20],
    type: BeraType.ADD_MULT,
    action: BeraAction.INDEP,
  },
  [Bera.BUILDER]: {
    name: "Builder",
    description: "+{{value}} Mult if played hand contains a Four of a Straight",
    cost: 4,
    rarity: BeraRarity.COMMON,
    values: [12, 16, 20],
    type: BeraType.ADD_MULT,
    action: BeraAction.INDEP,
  },
  [Bera.COLORLESS]: {
    name: "Colorless",
    description: "+{{value}} Mult if played hand contains a Flush",
    cost: 4,
    rarity: BeraRarity.COMMON,
    values: [10, 15, 20],
    type: BeraType.ADD_MULT,
    action: BeraAction.INDEP,
  },
  [Bera.PERFECTION]: {
    name: "Perfection",
    description:
      "Each played 10 gives +{{value}} Chips when scored if only 10 played",
    cost: 8,
    rarity: BeraRarity.RARE,
    values: [100, 150, 200],
    type: BeraType.ADD_CHIPS,
    action: BeraAction.ON_SCORED,
  },
  [Bera.MUSKETEERS]: {
    name: "Musketeers",
    description:
      "x{{value}} Mult if played hand contains a Three of a Kind of J",
    cost: 8,
    rarity: BeraRarity.RARE,
    values: [3, 4, 5],
    type: BeraType.MUL_MULT,
    action: BeraAction.INDEP,
  },
  [Bera.MOTHER_CARE]: {
    name: "Mother Care",
    description:
      " 1 in {{value}} chance for each played Q to create a Flower card when scored",
    cost: 8,
    rarity: BeraRarity.RARE,
    values: [3, 2, 1],
    type: BeraType.GEN_FLOWER,
    action: BeraAction.ON_SCORED,
  },
  [Bera.CROWN]: {
    name: "Crown",
    description: "Each King held in hand gives x{{value}} Mult",
    cost: 8,
    rarity: BeraRarity.RARE,
    values: [1.5, 2, 2.5],
    type: BeraType.MUL_MULT,
    action: BeraAction.ON_HELD,
  },
  [Bera.AIRDROP]: {
    name: "Airdrop",
    description: "Gains x{{value}} Mult for every A that is removed",
    cost: 8,
    rarity: BeraRarity.RARE,
    values: [1, 1.5, 2],
    type: BeraType.MUL_MULT,
    action: BeraAction.INDEP,
  },
  [Bera.CHIP]: {
    name: "Chip",
    description: "+{{value}} Mult if played hand contains 3 or fewer cards",
    cost: 5,
    rarity: BeraRarity.COMMON,
    values: [20, 30, 40],
    type: BeraType.ADD_MULT,
    action: BeraAction.INDEP,
  },
  [Bera.CRAWL]: {
    name: "Crawl",
    description: "x{{value}} Mult if played hand contains 4 cards",
    cost: 5,
    rarity: BeraRarity.UNCOMMON,
    values: [2, 3, 4],
    type: BeraType.MUL_MULT,
    action: BeraAction.INDEP,
  },
  [Bera.MAGNET]: {
    name: "Magnet",
    description: "x{{value}} Mult each played card without scoring",
    cost: 6,
    rarity: BeraRarity.UNCOMMON,
    values: [1.5, 2, 2.5],
    type: BeraType.MUL_MULT,
    action: BeraAction.INDEP,
  },
  [Bera.BAG]: {
    name: "Bag",
    description: "+{{value}} hand size, reduces by 1 each round",
    cost: 6,
    rarity: BeraRarity.UNCOMMON,
    values: [5, 7, 10],
    type: BeraType.ADD_GOLD,
    action: BeraAction.ON_HELD,
  },
  [Bera.SCARF]: {
    name: "Scarf",
    description: "+{{value}} Chips for each remaining discard",
    cost: 5,
    rarity: BeraRarity.COMMON,
    values: [30, 40, 50],
    type: BeraType.ADD_CHIPS,
    action: BeraAction.INDEP,
  },
  [Bera.HAT]: {
    name: "Hat",
    description:
      "Each {{value}} card held in hand has a 1 in {{value}} chance to give $1",
    cost: 5,
    rarity: BeraRarity.COMMON,
    values: [3, 2, 1],
    type: BeraType.ADD_GOLD,
    action: BeraAction.ON_HELD,
  },
  [Bera.LUSCIOUS]: {
    name: "Luscious",
    description: "Gains x{{value}} Mult every time a Flower is used",
    cost: 6,
    rarity: BeraRarity.UNCOMMON,
    values: [0.1, 0.2, 0.3],
    type: BeraType.MUL_MULT,
    action: BeraAction.INDEP,
  },
  [Bera.BADGE]: {
    name: "Gains {{value}} every time a playing card is added to the deck",
    description: "BADGE",
    cost: 7,
    rarity: BeraRarity.UNCOMMON,
    values: [0.25, 0.5, 0.75],
    type: BeraType.MUL_MULT,
    action: BeraAction.INDEP,
  },
  [Bera.SHY]: {
    name: "Shy",
    description: "+{{value}} Mult if played hand contains no face card",
    cost: 3,
    rarity: BeraRarity.UNCOMMON,
    values: [20, 30, 40],
    type: BeraType.ADD_MULT,
    action: BeraAction.INDEP,
  },
  [Bera.NOPE]: {
    name: "Nope",
    description: "Gains x{{value}} Mult when any Booster Pack is skipped",
    cost: 6,
    rarity: BeraRarity.UNCOMMON,
    values: [0.1, 0.2, 0.3],
    type: BeraType.MUL_MULT,
    action: BeraAction.INDEP,
  },
  [Bera.BIG_TINY]: {
    name: "Big Tiny",
    description: "Retrigger {{value}} times all played cards less than 10",
    cost: 6,
    rarity: BeraRarity.UNCOMMON,
    values: [1, 2, 3],
    type: BeraType.MUL_MULT,
    action: BeraAction.INDEP,
  },
  [Bera.GIFT]: {
    name: "Gift",
    description: "Earn ${{value}} at end of round",
    cost: 6,
    rarity: BeraRarity.COMMON,
    values: [4, 6, 8],
    type: BeraType.ADD_GOLD,
    action: BeraAction.ON_ENDED,
  },
  [Bera.FISH]: {
    name: "Fish",
    description: "FISH",
    cost: 4,
    rarity: BeraRarity.RARE,
    values: [2, 3, 4],
    type: BeraType.GEN_FLOWER,
    action: BeraAction.ON_SCORED,
  },
  [Bera.BAKER]: {
    name: "Baker",
    description: "BAKER",
    cost: 5,
    rarity: BeraRarity.EPIC,
    values: [2, 3, 4],
    type: BeraType.GEN_MEME,
    action: BeraAction.ON_REMOVED,
  },
  [Bera.SMILE]: {
    name: "Smile",
    description: "Common Jokers each give x{{value}} Mult",
    cost: 6,
    rarity: BeraRarity.UNCOMMON,
    values: [1, 1.5, 2],
    type: BeraType.MUL_MULT,
    action: BeraAction.INDEP,
  },
  [Bera.STAR]: {
    name: "Star",
    description: "STAR",
    cost: 6,
    rarity: BeraRarity.LEGENDARY,
    values: [3, 4, 5],
    type: BeraType.ADD_MULT,
    action: BeraAction.ON_SCORED,
  },
  [Bera.DROOL]: {
    name: "Drool",
    description: "DROOL",
    cost: 3,
    rarity: BeraRarity.COMMON,
    values: [1, 2, 3],
    type: BeraType.ADD_CHIPS,
    action: BeraAction.ON_HELD,
  },
  [Bera.SLEEP]: {
    name: "Sleep",
    description: "SLEEP",
    cost: 4,
    rarity: BeraRarity.RARE,
    values: [2, 3, 4],
    type: BeraType.MUL_MULT,
    action: BeraAction.ON_DISCARD,
  },
  [Bera.STRONG]: {
    name: "Strong",
    description:
      "Every played card permanently gains +{{value}} Chips when scored",
    cost: 5,
    rarity: BeraRarity.UNCOMMON,
    values: [5, 10, 15],
    type: BeraType.INCREASE_CHIPS,
    action: BeraAction.ON_SCORED,
  },
  [Bera.CLOUD]: {
    name: "Cloud",
    description: "Earn ${{value}} for each 9 in your full deck at end of round",
    cost: 7,
    rarity: BeraRarity.UNCOMMON,
    values: [1, 2, 3],
    type: BeraType.ADD_GOLD,
    action: BeraAction.ON_ENDED,
  },
  [Bera.SOCKS]: {
    name: "Socks",
    description: "SOCKS",
    cost: 4,
    rarity: BeraRarity.RARE,
    values: [2, 3, 4],
    type: BeraType.GEN_MEME,
    action: BeraAction.ON_PLAYED,
  },
  [Bera.X]: {
    name: "X",
    description:
      "Earn ${{value}} for each discarded [rank], rank changes every round",
    cost: 4,
    rarity: BeraRarity.COMMON,
    values: [5, 7, 10],
    type: BeraType.ADD_GOLD,
    action: BeraAction.ON_DISCARD,
  },
};

// TypeScript type for the stats
export type BeraStats = {
  name: string;
  description: string;
  cost: number;
  rarity: BeraRarity;
  values: [number, number, number]; // tuple of 3 numbers
  type: BeraType;
  action: BeraAction;
};
